sudo: required
services:
  - docker

before_install:
  - docker build -t galal/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run galal/react-test npm test -- --coverage

after_success:
  - docker build -t galal/multi-client ./client
  - docker build -t galal/multi-nginx ./nginx
  - docker build -t galal/multi-server ./server
  - docker build -t galal/multi-worker ./worker
  # Log in to the docker CLI
  #- echo "$DOCKERPASS" | docker login -u "$DOCKERID" --password-stdin
  - echo "$DOCKERPASS" | docker login --username "$DOCKERID" --password-stdin
  - docker push galal/multi-client
  - docker push galal/multi-nginx
  - docker push galal/multi-server
  - docker push galal/multi-worker

# deploy:
#   provider: elasticbeanstalk
#   region: us-west-1
#   app: multi-docker
#   env: MultiDocker-env
#   bucket_name: elasticbeanstalk-us-west-1-306476627547
#   bucket_path: docker-multi
  on:
    branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: $AWS_SECRET_KEY
